"""initial schema

Revision ID: 1d39f6eeaae8
Revises: 
Create Date: 2026-05-30 20:18:55.623545
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

CREATE_IMMUTABLE_FUNCTION_SQL = """
CREATE OR REPLACE FUNCTION pulsepress_block_immutable_mutation()
RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION USING
        ERRCODE = '55000',
        MESSAGE = TG_TABLE_NAME || ' is immutable and cannot be updated or deleted';
END;
$$ LANGUAGE plpgsql
"""

DROP_IMMUTABLE_FUNCTION_SQL = "DROP FUNCTION IF EXISTS pulsepress_block_immutable_mutation()"

CREATE_IMMUTABLE_TRIGGERS_SQL = (
    "DO $$\nBEGIN\n"
    + "\n".join(
        f"""
    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger WHERE tgname = 'block_immutable_mutation_{table}'
    ) THEN
        CREATE TRIGGER block_immutable_mutation_{table}
        BEFORE UPDATE OR DELETE ON {table}
        FOR EACH ROW EXECUTE FUNCTION pulsepress_block_immutable_mutation();
    END IF;
"""
        for table in (
            "ledger_transactions",
            "ledger_entries",
            "post_versions",
            "reconciliation_log",
        )
    )
    + "END $$"
)

revision: str = '1d39f6eeaae8'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(CREATE_IMMUTABLE_FUNCTION_SQL)
    op.create_table('event_processing_attempts',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("status IN ('started', 'succeeded', 'failed')", name=op.f('ck_event_processing_attempts_status_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_processing_attempts'))
    )
    op.create_index(op.f('ix_event_processing_attempts_event_id'), 'event_processing_attempts', ['event_id'], unique=False)
    op.create_table('outbox_events',
    sa.Column('aggregate_type', sa.String(length=64), nullable=False),
    sa.Column('aggregate_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('event_version', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('publish_attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'published', 'failed', 'superseded', 'discarded')", name=op.f('ck_outbox_events_status_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox_events'))
    )
    op.create_index(op.f('ix_outbox_events_created_at'), 'outbox_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_outbox_events_event_type'), 'outbox_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_outbox_events_status'), 'outbox_events', ['status'], unique=False)
    op.create_table('users',
    sa.Column('cognito_sub', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('cognito_sub', name=op.f('uq_users_cognito_sub'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_table('idempotency_keys',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_idempotency_keys_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_idempotency_keys')),
    sa.UniqueConstraint('user_id', 'key', name='user_key_unique')
    )
    op.create_index(op.f('ix_idempotency_keys_user_id'), 'idempotency_keys', ['user_id'], unique=False)
    op.create_table('publications',
    sa.Column('owner_user_id', sa.Uuid(), nullable=False),
    sa.Column('handle', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(length=1024), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_publications_owner_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_publications')),
    sa.UniqueConstraint('handle', name=op.f('uq_publications_handle'))
    )
    op.create_index(op.f('ix_publications_owner_user_id'), 'publications', ['owner_user_id'], unique=False)
    op.create_table('reconciliation_log',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('admin_user_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('state_before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('state_after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("action IN ('retry', 'amend', 'discard', 'manual_fix')", name=op.f('ck_reconciliation_log_action_valid')),
    sa.CheckConstraint('char_length(reason) >= 10', name=op.f('ck_reconciliation_log_reason_min_length')),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], name=op.f('fk_reconciliation_log_admin_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reconciliation_log'))
    )
    op.create_index(op.f('ix_reconciliation_log_admin_user_id'), 'reconciliation_log', ['admin_user_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_log_event_id'), 'reconciliation_log', ['event_id'], unique=False)
    op.create_table('gift_transactions',
    sa.Column('sender_user_id', sa.Uuid(), nullable=False),
    sa.Column('publication_id', sa.Uuid(), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'processed', 'failed')", name=op.f('ck_gift_transactions_status_valid')),
    sa.CheckConstraint('amount_cents >= 50', name=op.f('ck_gift_transactions_amount_min')),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], name=op.f('fk_gift_transactions_publication_id_publications')),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], name=op.f('fk_gift_transactions_sender_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gift_transactions'))
    )
    op.create_index(op.f('ix_gift_transactions_publication_id'), 'gift_transactions', ['publication_id'], unique=False)
    op.create_index(op.f('ix_gift_transactions_sender_user_id'), 'gift_transactions', ['sender_user_id'], unique=False)
    op.create_table('ledger_transactions',
    sa.Column('publication_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('source_event_id', sa.Uuid(), nullable=False),
    sa.Column('principal_amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('author_net_cents', sa.BigInteger(), nullable=False),
    sa.Column('platform_fee_cents', sa.BigInteger(), nullable=False),
    sa.Column('tax_cents', sa.BigInteger(), nullable=False),
    sa.Column('total_charged_cents', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("source_type IN ('subscription', 'gift')", name=op.f('ck_ledger_transactions_source_type_valid')),
    sa.CheckConstraint('author_net_cents + platform_fee_cents + tax_cents = total_charged_cents', name=op.f('ck_ledger_transactions_balanced_total')),
    sa.CheckConstraint('principal_amount_cents + tax_cents = total_charged_cents', name=op.f('ck_ledger_transactions_principal_plus_tax')),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], name=op.f('fk_ledger_transactions_publication_id_publications')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_transactions')),
    sa.UniqueConstraint('source_type', 'source_id', name='source_unique')
    )
    op.create_index(op.f('ix_ledger_transactions_publication_id'), 'ledger_transactions', ['publication_id'], unique=False)
    op.create_table('notification_events',
    sa.Column('publication_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], name=op.f('fk_notification_events_publication_id_publications')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_events'))
    )
    op.create_index(op.f('ix_notification_events_publication_id'), 'notification_events', ['publication_id'], unique=False)
    op.create_table('posts',
    sa.Column('publication_id', sa.Uuid(), nullable=False),
    sa.Column('author_user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('slug', sa.String(length=512), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'published', 'archived')", name=op.f('ck_posts_status_valid')),
    sa.CheckConstraint("visibility IN ('free', 'paid')", name=op.f('ck_posts_visibility_valid')),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], name=op.f('fk_posts_author_user_id_users')),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], name=op.f('fk_posts_publication_id_publications')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_posts'))
    )
    op.create_index(op.f('ix_posts_author_user_id'), 'posts', ['author_user_id'], unique=False)
    op.create_index(op.f('ix_posts_publication_id'), 'posts', ['publication_id'], unique=False)
    op.create_table('publication_daily_stats',
    sa.Column('publication_id', sa.Uuid(), nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.Column('subscriber_count', sa.Integer(), nullable=False),
    sa.Column('gift_count', sa.Integer(), nullable=False),
    sa.Column('post_count', sa.Integer(), nullable=False),
    sa.Column('gross_revenue_cents', sa.BigInteger(), nullable=False),
    sa.Column('author_net_cents', sa.BigInteger(), nullable=False),
    sa.Column('platform_fees_cents', sa.BigInteger(), nullable=False),
    sa.Column('tax_collected_cents', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], name=op.f('fk_publication_daily_stats_publication_id_publications')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_publication_daily_stats')),
    sa.UniqueConstraint('publication_id', 'stat_date', name='publication_date_unique')
    )
    op.create_index(op.f('ix_publication_daily_stats_publication_id'), 'publication_daily_stats', ['publication_id'], unique=False)
    op.create_table('subscription_plans',
    sa.Column('publication_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('monthly_price_cents', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('allow_open_amount', sa.Boolean(), nullable=False),
    sa.Column('benefits', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], name=op.f('fk_subscription_plans_publication_id_publications')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscription_plans'))
    )
    op.create_index(op.f('ix_subscription_plans_publication_id'), 'subscription_plans', ['publication_id'], unique=False)
    op.create_table('user_feed_events',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('publication_id', sa.Uuid(), nullable=False),
    sa.Column('source_event_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], name=op.f('fk_user_feed_events_publication_id_publications')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_feed_events_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_feed_events'))
    )
    op.create_index(op.f('ix_user_feed_events_publication_id'), 'user_feed_events', ['publication_id'], unique=False)
    op.create_index('ix_user_feed_events_user_created', 'user_feed_events', ['user_id', 'created_at'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('ledger_transaction_id', sa.Uuid(), nullable=False),
    sa.Column('publication_id', sa.Uuid(), nullable=False),
    sa.Column('account', sa.String(length=16), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("account IN ('author', 'platform', 'tax')", name=op.f('ck_ledger_entries_account_valid')),
    sa.CheckConstraint("direction IN ('credit')", name=op.f('ck_ledger_entries_direction_valid')),
    sa.ForeignKeyConstraint(['ledger_transaction_id'], ['ledger_transactions.id'], name=op.f('fk_ledger_entries_ledger_transaction_id_ledger_transactions')),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], name=op.f('fk_ledger_entries_publication_id_publications')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_entries')),
    sa.UniqueConstraint('ledger_transaction_id', 'account', name='transaction_account_unique')
    )
    op.create_index(op.f('ix_ledger_entries_ledger_transaction_id'), 'ledger_entries', ['ledger_transaction_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_publication_id'), 'ledger_entries', ['publication_id'], unique=False)
    op.create_table('newsletter_sends',
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('publication_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('recipient_count_sim', sa.BigInteger(), nullable=False),
    sa.Column('artifact_s3_key', sa.String(length=1024), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("status IN ('requested', 'sent', 'failed')", name=op.f('ck_newsletter_sends_status_valid')),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_newsletter_sends_post_id_posts')),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], name=op.f('fk_newsletter_sends_publication_id_publications')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_newsletter_sends'))
    )
    op.create_index(op.f('ix_newsletter_sends_post_id'), 'newsletter_sends', ['post_id'], unique=False)
    op.create_index(op.f('ix_newsletter_sends_publication_id'), 'newsletter_sends', ['publication_id'], unique=False)
    op.create_table('post_versions',
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('snapshotted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_post_versions_post_id_posts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post_versions'))
    )
    op.create_index(op.f('ix_post_versions_post_id'), 'post_versions', ['post_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('subscriber_user_id', sa.Uuid(), nullable=False),
    sa.Column('publication_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('access_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'canceled', 'expired')", name=op.f('ck_subscriptions_status_valid')),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], name=op.f('fk_subscriptions_plan_id_subscription_plans')),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], name=op.f('fk_subscriptions_publication_id_publications')),
    sa.ForeignKeyConstraint(['subscriber_user_id'], ['users.id'], name=op.f('fk_subscriptions_subscriber_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions'))
    )
    op.create_index(op.f('ix_subscriptions_plan_id'), 'subscriptions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_publication_id'), 'subscriptions', ['publication_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_subscriber_user_id'), 'subscriptions', ['subscriber_user_id'], unique=False)
    op.create_index('uq_active_subscriber_publication', 'subscriptions', ['subscriber_user_id', 'publication_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.execute(CREATE_IMMUTABLE_TRIGGERS_SQL)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_active_subscriber_publication', table_name='subscriptions', postgresql_where=sa.text("status = 'active'"))
    op.drop_index(op.f('ix_subscriptions_subscriber_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_publication_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_plan_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_post_versions_post_id'), table_name='post_versions')
    op.drop_table('post_versions')
    op.drop_index(op.f('ix_newsletter_sends_publication_id'), table_name='newsletter_sends')
    op.drop_index(op.f('ix_newsletter_sends_post_id'), table_name='newsletter_sends')
    op.drop_table('newsletter_sends')
    op.drop_index(op.f('ix_ledger_entries_publication_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_ledger_transaction_id'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index('ix_user_feed_events_user_created', table_name='user_feed_events')
    op.drop_index(op.f('ix_user_feed_events_publication_id'), table_name='user_feed_events')
    op.drop_table('user_feed_events')
    op.drop_index(op.f('ix_subscription_plans_publication_id'), table_name='subscription_plans')
    op.drop_table('subscription_plans')
    op.drop_index(op.f('ix_publication_daily_stats_publication_id'), table_name='publication_daily_stats')
    op.drop_table('publication_daily_stats')
    op.drop_index(op.f('ix_posts_publication_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_author_user_id'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_notification_events_publication_id'), table_name='notification_events')
    op.drop_table('notification_events')
    op.drop_index(op.f('ix_ledger_transactions_publication_id'), table_name='ledger_transactions')
    op.drop_table('ledger_transactions')
    op.drop_index(op.f('ix_gift_transactions_sender_user_id'), table_name='gift_transactions')
    op.drop_index(op.f('ix_gift_transactions_publication_id'), table_name='gift_transactions')
    op.drop_table('gift_transactions')
    op.drop_index(op.f('ix_reconciliation_log_event_id'), table_name='reconciliation_log')
    op.drop_index(op.f('ix_reconciliation_log_admin_user_id'), table_name='reconciliation_log')
    op.drop_table('reconciliation_log')
    op.drop_index(op.f('ix_publications_owner_user_id'), table_name='publications')
    op.drop_table('publications')
    op.drop_index(op.f('ix_idempotency_keys_user_id'), table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_outbox_events_status'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_event_type'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_created_at'), table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_index(op.f('ix_event_processing_attempts_event_id'), table_name='event_processing_attempts')
    op.drop_table('event_processing_attempts')
    op.execute(DROP_IMMUTABLE_FUNCTION_SQL)
    # ### end Alembic commands ###
